# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            ingben
tagline:          'Hacking, Boardgames, Kites, Stuff'
description:      'A blog about the stuff I do.'
url:              http://ingben.github.io
paginate:         5

author:
  name:           'Ingo Bente'
#  url:            https://plus.google.com/u/0/106970872378113969694/

# Custom vars
version:          0.0.1

github:           
  repo:           https://github.com/ingben/
