# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            ingben
tagline:          'hacking, boardgames, kites, stuff'
description:      'A blog about the stuff I do.'
url:              http://ingben.github.io
#baseurl:          /ingben
paginate:         5

author:
  name:           'Ingo Bente'

# Custom vars
version:          0.0.1

github:           https://github.com/ingben/

archive:          '/archive'
