# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            ingben
tagline:          'Hacking, Boardgames, Kites, Stuff'
description:      'A blog about the stuff I do.'
url:              http://ingben.github.io
paginate:         5

pages_list:
	about: '/about'
	archive: '/archive'
	feed: '/atom.xml'

author:
  name:           'Ingo Bente'

# Custom vars
version:          0.0.1

github:           
  repo:           https://github.com/ingben/
